SELECT * FROM Member;
DESC Member;

DELETE FROM Board
WHERE memberId NOT IN(
SELECT id FROM Member);

ALTER TABLE Board
ADD FOREIGN KEY (MemberId)
REFERENCES Member(id);


CREATE TABLE Board
(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	body VARCHAR(2047) NOT NULL,
    memberId VARCHAR(255) NOT NULL,
    inserted TIMESTAMP DEFAULT NOW()
);
DROP table Borad;
DESC Board;
SELECT * FROM Board;
SELECT * FROM Member;